on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Core
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./BlueBirdDX/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            NuGet_SourceUrl=https://nuget.pkg.github.com/oatmealdome/index.json
            NuGet_SourceUserName=${{ github.repository_owner }}
            NuGet_SourcePassword=${{ secrets.GHCR_INSTALL_PAT }}
          tags: |
            ghcr.io/oatmealdome/bluebirddx:latest
      - name: Build WebApp
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./BlueBirdDX.WebApp/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            NuGet_SourceUrl=https://nuget.pkg.github.com/oatmealdome/index.json
            NuGet_SourceUserName=${{ github.repository_owner }}
            NuGet_SourcePassword=${{ secrets.GHCR_INSTALL_PAT }}
          tags: |
            ghcr.io/oatmealdome/bluebirddxwebapp:latest
