on:
  release:
    types:
      - published

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Core
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./BlueBirdDX/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            NuGet_SourceUrl=https://nuget.pkg.github.com/oatmealdome/index.json
            NuGet_SourceUserName=${{ github.repository_owner }}
            NuGet_SourcePassword=${{ secrets.GHCR_INSTALL_PAT }}
          tags: |
            ghcr.io/oatmealdome/bluebirddx:latest
      - name: Build WebApp
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./BlueBirdDX.WebApp/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            NuGet_SourceUrl=https://nuget.pkg.github.com/oatmealdome/index.json
            NuGet_SourceUserName=${{ github.repository_owner }}
            NuGet_SourcePassword=${{ secrets.GHCR_INSTALL_PAT }}
          tags: |
            ghcr.io/oatmealdome/bluebirddxwebapp:latest
      - name: Build TextWrapper
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./BlueBirdDX.TextWrapper/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            NuGet_SourceUrl=https://nuget.pkg.github.com/oatmealdome/index.json
            NuGet_SourceUserName=${{ github.repository_owner }}
            NuGet_SourcePassword=${{ secrets.GHCR_INSTALL_PAT }}
          tags: |
            ghcr.io/oatmealdome/bluebirddxtextwrapper:latest
  api-library-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      
      - name: Clear NuGet Caches
        run: dotnet nuget locals all --clear
      
      - name: Setup NuGet Source
        run: dotnet nuget add source "https://nuget.pkg.github.com/oatmealdome/index.json" --name ghcr --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

      - name: Install dependencies
        run: dotnet restore --configfile nuget-ci.config
        env:
          NuGet_SourceUrl: https://nuget.pkg.github.com/oatmealdome/index.json
          NuGet_SourceUserName: ${{ github.repository_owner }}
          NuGet_SourcePassword: ${{ secrets.GHCR_INSTALL_PAT }}
        
      - name: Build
        run: dotnet build BlueBirdDX.PublicApi/BlueBirdDX.PublicApi.csproj --configuration Release --no-restore
      
      - name: Pack
        if: github.event_name == 'release'
        run: dotnet pack BlueBirdDX.PublicApi/BlueBirdDX.PublicApi.csproj /p:Version=${{ github.event.release.tag_name }} --configuration Release --no-restore --verbosity normal --output .
      
      - name: Push to NuGet Source
        if: github.event_name == 'release'
        run: dotnet nuget push *.nupkg --source ghcr
